### ISSUE TITLE
Error fetching from binance exchange

### ISSUE THREAD

**Issue by iamashwin99** [MarcinOrlowski/crypto-tracker-plasmoid#22]
Binance is one of the leading crypto exchange it would be nice if we could pull data from Binance

I looked through the source code and found the structure of the var exchanges
so I added the following object to it
```
'binance-com': {
		name: 'Binance',
		url: 'https://api1.binance.com/',
		getRateFromExchangeData: function(data, crypto, fiat) {
            
			return data[0].price
		},
		getUrl: function(crypto, fiat) {
			url= 'https://api1.binance.com/api/v3/trades?symbol=' + crypto + fiat +'&limit=1'
                        console.error(url)
                        return url
		},
		pairs: {
			BTC: [
				'USDT',
				'EUR',
				'GBP',
				'JPY',
			],
			ETH: [
				'USDT',
				'EUR',
				'GBP',
				'JPY',
			],
			ETC: [
				'USDT',
				'EUR',
			],
			LTC: [
				'USDT',
				'EUR',
				'GBP',
				'JPY',
			],
			XRP: [
				'USDT',
				'EUR',
				'GBP',
				'JPY',
			],
		}
	}
```

This added the binance exchange but it couldn't fetch the data correctly.
I ran` journalctl /usr/bin/plasmashell `to see if the `console.error() `was pushed but I couldn't find it.

Any help would be greatly appreciated

**Comment by MarcinOrlowski** [comment]
You may want to test your changes using plasmaviewer instead. There's bunch of helpers I created https://github.com/marcinorlowski/plasmoid-tools that may come handy.

**Comment by MarcinOrlowski** [comment]
I already added binance support in developer build: https://github.com/MarcinOrlowski/crypto-tracker-plasmoid/pull/24
