### ISSUE TITLE
Price refresh in steps of seconds instead of minutes

### ISSUE THREAD

**Issue by wanixarif** [MarcinOrlowski/crypto-tracker-plasmoid#33]

**Comment by MarcinOrlowski** [comment]
I do not see a point really. Most API throttle access anyway.

**Comment by wanixarif** [comment]
> I do not see a point really. Most API throttle access anyway.

Can you point out the line no. + fileName that sets the refresh rate.
I don't know qml or gui stuff but if you point it out I'd edit it for myself locally

**Comment by MarcinOrlowski** [comment]
Here: https://github.com/MarcinOrlowski/crypto-tracker-plasmoid/blob/master/src/contents/ui/Exchange.qml#L331

**Comment by wanixarif** [comment]
> Here: https://github.com/MarcinOrlowski/crypto-tracker-plasmoid/blob/master/src/contents/ui/Exchange.qml#L331
> 
> ```qml
> Timer {
> 	interval: refreshRate * 60 * 1000
> ```
> 
> if you remove `60` you will have your settings interpreted as seconds (keep in mind that you cannot go faster that single request needs to complete).

Thanks a lot :)
