### ISSUE TITLE
Fiat currency not selectable

### ISSUE THREAD

**Issue by othbert** [MarcinOrlowski/crypto-tracker-plasmoid#7]
**What's wrong?**
Currency appears to default to the first in the list for a given exchange, the selection opens when clicked but not possible to choose from the options.

**Steps to reproduce the behavior:**
 1. Add a crypto to track
 2. Choose an exchange
 3. Attempt to change fiat currency representation

**Expected behavior**
The clicked currency should be selected. 

**Runtime environment**
 - Widget version (see About dialog) 
v.1.1.0
 - Plasma version (output of `plasmashell --version`)
plasmashell 5.21.0
 - Name and version of OS: (just paste output of `lsb_release -d`)
openSUSE Tumbleweed
 - If you use non-standard dock (i.e. Latte), put its name.
N/A

**Notes**
Any additional information that may be helpful diagnosing the problem.

Thanks for making this tracker! Additionally, the crypto value does not update when applying changes, it waits until the next refresh. Not really a bug, but would be cool to see changes reflected immediately via a call to refresh the plasmoid.

**Comment by MarcinOrlowski** [comment]
I cannot confirm this. Please be more precise - what exchange and what crypto? Also note each exchange can have different pairs for each crypto.

**Comment by othbert** [comment]
Oh that's interesting, happened for me with all and every exchange and crypto. Could not select any fiat except the one that happened to be first in the list, whether that was PZ, CZ or USD. For example, ETH on Kraken, defaults to USD for me and unchangeable.

**Comment by MarcinOrlowski** [comment]
There's logic that watches exchange/crypto/fiat changes to ensure your config is always valid for given combination and if not (i.e. you switched from Bitbay to Kraken which does not support PLN, it would fall back to first supported fiat for specified crypto on Kraken) so there's a chance there's something there that makes it malfunction in some cases, but for now I am unable to reproduce this locally. Have used 1.0.0 and then upgraded to 1.1.0 or it's your fresh installation?

**Comment by othbert** [comment]
This is on a brand new install via plasma panel's add widgets -> get new widgets dialog.
Yeah, the list of supported fiat changed correctly per exchange and crypto, and the dropdown opens, just that after clicking one, e.g. EUR for ETH @ Kraken, the dropdown would close and USD would still be selected.
I don't know if this is any help, but the dropdowns do not behave quite like other plasma settings dialogs. There is no indication by highlighting which row in the dropdown is selected as you hover over them, and keyboard navigation in the rows does not appear to work for me.

**Comment by MarcinOrlowski** [comment]
Good news. I managed to reproduce the issue.

**Comment by othbert** [comment]
Thanks, works perfectly now!

**Comment by MarcinOrlowski** [comment]
Great. Thanks for reporting the issue.
